echo on
%DURBIN_WATSONDEMO Demo of DURBIN_WATSON
 
echo off
%Copyright Eigenvector Research, Inc. 2002
%Licensee shall not re-compile, translate or convert "M-files" contained
% in PLS_Toolbox for use with any software other than MATLAB®, without
% written permission from Eigenvector Research, Inc.
%ww 06/11/04 Initial coding.
 
echo on
 
%To run the demo hit a "return" after each pause
pause
%-------------------------------------------------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%DURBIN_WATSON generates numbers that are a measure of continuity.
%Low values indicate a continuous type of signal, high values indicate a
%random type of signal. As a demonstration we will use a Raman data set
%of which we know it has four components. One can assume than that the
%first four loading patterns created by the Matlab function SVD are
%continuous, while the remaining loading patterns represent noise.
%We will plot the first six loading patterns.
pause
%-------------------------------------------------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
load raman_time_resolved
[u,s,v]=svd(raman_time_resolved.data,0);
figure;
subplot(331);plot(raman_time_resolved.axisscale{2},v(:,1));title('1');set(gca,'xticklabel',[]);
subplot(332);plot(raman_time_resolved.axisscale{2},v(:,2));title('2');set(gca,'xticklabel',[]);
subplot(333);plot(raman_time_resolved.axisscale{2},v(:,3));title('3');set(gca,'xticklabel',[]);
subplot(334);plot(raman_time_resolved.axisscale{2},v(:,4));title('4');set(gca,'xticklabel',[]);
subplot(335);plot(raman_time_resolved.axisscale{2},v(:,5));title('5');set(gca,'xticklabel',[]);
subplot(336);plot(raman_time_resolved.axisscale{2},v(:,6));title('6');set(gca,'xticklabel',[]);
 
%It is clear from the visual inspection that the first four loading
%patterns indeed reflect a continuous pattern, while the remaining two
%reflect a noisy pattern. We will now generate a plot with the values
%generated by the function DURBIN_WATSON for all 16 eigenvectors of this
%data set. The number of eigenvectors is determined by min(size(raman_time_resolved))
pause
%-------------------------------------------------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
db=durbin_watson(v(:,1:16));
subplot(338);plot(db,'-*');axis tight
%It is clear that the values generated by DURBIN_WATSON reflect the
%continuity of the data. The DURBIN_WATSON function is the key function in
%the CODA_DW function.
pause
