echo on
% RWBDEMO Demo of the RWB function
 
echo off
% Copyright © Eigenvector Research, Inc. 2002
% Licensee shall not re-compile, translate or convert "M-files" contained
%  in PLS_Toolbox for use with any software other than MATLAB¨, without
%  written permission from Eigenvector Research, Inc.
%bmw
 
echo on
 
% To run the demo hit a "return" after each pause
pause
%-------------------------------------------------
%  RWB creates a red to white to blue colormap, useful for plotting
%  when only high and low values are to be highlighted, (such as 
%  those generated by CORRMAP). The optional input (m) specifies the 
%  length of the colormap. With no inputs, RWB returns a colormap the same
%  length as the current colormap. The output (map) is the 
%  m-by-3 colormap matrix.
pause
%-------------------------------------------------
% As an example consider the MATLAB PEAKS function using the default
% colormap of HSV:
 
figure
imagesc(peaks), colormap(hsv), colorbar
 
pause
%-------------------------------------------------
% This can be changed to the RWB colormap using:
 
colormap(rwb)
 
pause
%-------------------------------------------------
% To bring the m by 3 colormap into the workspace, call it with an
% output as in the following example:
 
colormap16 = rwb(16)
 
echo off
