function ktool(msg)
%KTOOL GUI tool for investigating the density of a sample.
%
%I/O: ktool(x)
%
%See also: CQTOOL, PLOTCQQ, PLOTKD, PLOTQQ, QTOOL

%Copyright Eigenvector Research, Inc. 2006
%Licensee shall not re-compile, translate or convert "M-files" contained
% in PLS_Toolbox for use with any software other than MATLAB®, without
% written permission from Eigenvector Research, Inc.
%
%Acquired from TESS, Texas Environmental Software Solutions
% Version 1.0.0, January 1998

if nargin==0; msg = 'io'; end
if ischar(msg) & ismember(msg,evriio([],'validtopics'));
  options = [];
  if nargout==0; 
    evriio(mfilename);
  else;          
    out = evriio(mfilename);
  end
  return;
end

if nargin == 0, error('Must call with one real vector argument') ; end
if ~isstr(msg)
	if ~isreal(msg), error('Argument must be real.') ; end
	if ~isvec(msg),  error('Argument must be a vector.') ; end
	kstr.data = msg ;
	kstr.tra  = 0 ;
	if min(msg) < 0 
		kstr.tra = min(msg) - .0001 ; 
	end
	kstr.data = msg - kstr.tra ;
	msg = 'init' ;
end

if strcmp(msg,'redraw')
	clist = allchild(0) ;
	hfig = clist(find(clist==gcf)) ;
	kstr = get(hfig,'Userdata') ;
	if isempty(kstr) & strcmp(msg,'motion')
		return ;
	end

	kernel  = get(kstr.khandle,'Value') ;
	oval    = get(kstr.ohandle,'Value') ;
	ochr    = get(kstr.ohandle,'String') ;
	overlay = ochr{oval} ;
	width   = get(kstr.whandle,'Value') ;
	set(kstr.bw,'String',num2str(get(kstr.whandle,'Value'))) ;
	plotkd(kstr.data,overlay,kernel,width,kstr.tra) ;
end

if strcmp(msg,'init') 

	load ktool
	jmat4 = { ...
		'<NONE>',...
		'Beta',...
		'Cauchy',...
		'Chi Squared',...
		'Exponential',...
		'Gamma',...
		'Gumbel',...
		'Laplace',...
		'Logistic',...
		'Lognormal',...
		'Normal',...
		'Pareto',...
		'Rayleigh',...
		'Triangle',...
		'Uniform',...
		'Weibull' } ; 

	a = figure('Color',[0.8 0.8 0.8], ...
		'Colormap',mat0, ...
		'PointerShapeCData',mat1, ...
		'Position',[315 189 594 498], ...
		'Tag','Fig1', ...
		'UserData',mat2);
	kstr.fig = a ;
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'Position',[297 30.75 136.5 327.75], ...
		'Style','frame', ...
		'Tag','Frame1');
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'Callback','ktool(''redraw'')', ...
		'Position',[309.75 241.5 114 73.5], ...
		'String',mat3, ...
		'Style','listbox', ...
		'Tag','Listbox1', ...
		'Value',3);
	kstr.khandle = b ;
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'Callback','ktool(''redraw'')', ...
		'Position',[309 85.5 114 132.75], ...
		'String',jmat4, ...
		'Style','listbox', ...
		'Tag','Listbox2', ...
		'Value',11);
	kstr.ohandle = b ;
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[0.752941 0.752941 0.752941], ...
		'Callback','ktool(''redraw'')', ...
		'Max',3.11182, ...
		'Min',0.00311182, ...
		'Position',[311.25 48.75 114 14.25], ...
		'Style','slider', ...
		'Tag','Slider1', ...
		'Value',0.311182);
	wid = min(std(kstr.data),...
		(pctile1(kstr.data,75)-pctile1(kstr.data,25))...
		/1.349)*.9/length(kstr.data)^.2 ;
	set(b,'Min',wid./100) ;
	set(b,'Max',wid.*10) ;
	set(b,'Value',wid) ;
	kstr.whandle = b ;
	b = axes('Parent',a, ...
		'Units','points', ...
		'Box','on', ...
		'CameraUpVector',[0 1 0], ...
		'Color',[1 1 1], ...
		'ColorOrder',mat5, ...
		'Position',[25.5 57 261 289.5], ...
		'Tag','Axes1', ...
		'XColor',[0 0 0], ...
		'XLim',[3.51814 8.49437], ...
		'XLimMode','manual', ...
		'YColor',[0 0 0], ...
		'YLim',[0 0.45932], ...
		'YLimMode','manual', ...
		'ZColor',[0 0 0]);
	c = line('Parent',b, ...
		'Color',[0 0 1], ...
		'Marker','o', ...
		'Tag','Line2', ...
		'XData',mat6, ...
		'YData',mat7);
	c = line('Parent',b, ...
		'Color',[0 0.5 0], ...
		'Marker','x', ...
		'Tag','Line1', ...
		'XData',mat8, ...
		'YData',mat9);
	c = text('Parent',b, ...
		'Color',[0 0 0], ...
		'HandleVisibility','callback', ...
		'HorizontalAlignment','center', ...
		'Position',[3.00905 0.230853 0], ...
		'Rotation',90, ...
		'String',' ', ...
		'Tag','Text1', ...
		'VerticalAlignment','baseline');
	set(get(c,'Parent'), 'XLabel',c) ;
	c = text('Parent',b, ...
		'Color',[0 0 0], ...
		'HandleVisibility','callback', ...
		'HorizontalAlignment','center', ...
		'Position',[6.00626 0.46946 0], ...
		'String','Kernel density plot', ...
		'Tag','Text2', ...
		'VerticalAlignment','bottom');
	set(get(c,'Parent'), 'YLabel',c) ;
	c = text('Parent',b, ...
		'Color',[0 0 0], ...
		'HandleVisibility','callback', ...
		'HorizontalAlignment','center', ...
		'Position',[6.00626 -0.0268433 0], ...
		'Tag','Text3', ...
		'VerticalAlignment','cap');
	set(get(c,'Parent'),'ZLabel',c);
	c = text('Parent',b, ...
		'Color',[0 0 0], ...
		'HandleVisibility','callback', ...
		'HorizontalAlignment','right', ...
		'Position',[3.02339 0.502865 0], ...
		'Tag','Text4', ...
		'Visible','off');
	set(get(c,'Parent'),'Title',c);
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'FontWeight','demi', ...
		'HorizontalAlignment','left', ...
		'Position',[310.5 318.75 111 11.25], ...
		'String','Kernel', ...
		'Style','text', ...
		'Tag','StaticText1');
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'FontWeight','demi', ...
		'HorizontalAlignment','left', ...
		'Position',[309.75 223.5 111 11.25], ...
		'String','Overlay distribution', ...
		'Style','text', ...
		'Tag','StaticText1');
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'FontWeight','demi', ...
		'Position',[312 66.75 111 11.25], ...
		'String','Kernel Bandwidth', ...
		'Style','text', ...
		'Tag','StaticText1');
	kstr.bw = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'FontWeight','demi', ...
		'Position',[312 34.5 111 11.25], ...
		'String','0.31118', ...
		'Style','text', ...
		'Tag','StaticText1');
	kstr.wid = wid ;
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'FontSize',14, ...
		'FontWeight','bold', ...
		'ForegroundColor',[0 0 1], ...
		'Position',[321.75 336 84.75 15], ...
		'String','K Tool', ...
		'Style','text', ...
		'Tag','StaticText2');
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'Position',[107.25 8.25 89.25 22.5], ...
		'Callback','close', ...
		'String','Close', ...
		'Tag','Pushbutton1');
	kstr.wid = wid ;

	set(kstr.bw,'String',num2str(get(kstr.whandle,'Value'))) ;
	set(kstr.fig,'UserData',kstr) ;
	ktool('redraw') ;
end

