function qtool(msg)
%QTOOL GUI tool for investigating the QQ-plot.
%
%I/O: qtool(x)
%
%See also: KTOOL, PLOTCQQ, PLOTKD, PLOTQQ, CQTOOL

%Copyright Eigenvector Research, Inc. 2006
%Licensee shall not re-compile, translate or convert "M-files" contained
% in PLS_Toolbox for use with any software other than MATLAB®, without
% written permission from Eigenvector Research, Inc.
%
%Acquired from TESS, Texas Environmental Software Solutions
% Version 1.0.0, January 1998

if nargin==0; msg = 'io'; end
if ischar(msg) & ismember(msg,evriio([],'validtopics'));
  options = [];
  if nargout==0; 
    evriio(mfilename);
  else;          
    out = evriio(mfilename);
  end
  return;
end

if nargin == 0, error('Must call with one real vector argument') ; end

if ~isstr(msg)
		if ~isreal(msg), error('Argument must be real.') ; end
		if ~isvec(msg),  error('Argument must be a vector.') ; end
		kstr.tra = 0 ;
		if min(msg) < 0
			kstr.tra = min(msg) - .0001 ;
		end
		kstr.data = msg - kstr.tra ;
		msg = 'init' ;
end

if strcmp(msg,'redraw')
	clist = allchild(0) ;
	hfig = clist(find(clist==gcf)) ;
	kstr = get(hfig,'Userdata') ;
	if isempty(kstr) & strcmp(msg,'motion')
		return ;
	end


	oval    = get(kstr.ohandle,'Value') ;
	ochr    = get(kstr.ohandle,'String') ;
	overlay = ochr{oval} ;
	plotqq(kstr.data,overlay,kstr.tra) ;
end

if strcmp(msg,'init') 

	load qtool                             

	jmat9 = { ...
		'Beta',...
		'Cauchy',...
		'Chi Squared',...
		'Exponential',...
		'Gamma',...
		'Gumbel',...
		'Laplace',...
		'Logistic',...
		'Lognormal',...
		'Normal',...
		'Pareto',...
		'Rayleigh',...
		'Triangle',...
		'Uniform',...
		'Weibull' } ; 

	a = figure('Color',[0.8 0.8 0.8], ...
		'Colormap',mat0, ...
		'PointerShapeCData',mat1, ...
		'Position',[328 197 594 458], ...
		'Tag','Fig1', ...
		'UserData',mat2);
	kstr.fig = a ;
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'Position',[302.25 62.25 134.25 252], ...
		'Style','frame', ...
		'Tag','Frame1');
	b = axes('Parent',a, ...
		'Units','points', ...
		'Box','on', ...
		'CameraUpVector',[0 1 0], ...
		'Color',[1 1 1], ...
		'ColorOrder',mat3, ...
		'Position',[43.5 25.5 249.75 289.5], ...
		'Tag','Axes1', ...
		'XColor',[0 0 0], ...
		'XLim',[-2.48186 2.49437], ...
		'XLimMode','manual', ...
		'YColor',[0 0 0], ...
		'YLim',[0 0.45932], ...
		'YLimMode','manual', ...
		'ZColor',[0 0 0]);
	c = line('Parent',b, ...
		'Color',[0 0 1], ...
		'Marker','o', ...
		'Tag','Line2', ...
		'XData',mat4, ...
		'YData',mat5);
	c = line('Parent',b, ...
		'Color',[0 0.5 0], ...
		'Marker','x', ...
		'Tag','Line1', ...
		'XData',mat6, ...
		'YData',mat7);
	c = text('Parent',b, ...
		'Color',[0 0 0], ...
		'HandleVisibility','callback', ...
		'HorizontalAlignment','center', ...
		'Position',[-3.01395 0.22966 0], ...
		'Rotation',90, ...
		'String',' ', ...
		'Tag','Text1', ...
		'VerticalAlignment','baseline');
	set(get(c,'Parent'),'YLabel',c);
	c = text('Parent',b, ...
		'Color',[0 0 0], ...
		'HandleVisibility','callback', ...
		'HorizontalAlignment','center', ...
		'Position',[-0.00123865 0.46946 0], ...
		'String','Kernel density plot', ...
		'Tag','Text2', ...
		'VerticalAlignment','bottom');
	set(get(c,'Parent'),'Title',c);
	c = text('Parent',b, ...
		'Color',[0 0 0], ...
		'HandleVisibility','callback', ...
		'HorizontalAlignment','center', ...
		'Position',[-0.00123865 -0.0268433 0], ...
		'Tag','Text3', ...
		'VerticalAlignment','cap');
	set(get(c,'Parent'),'XLabel',c);
	c = text('Parent',b, ...
		'Color',[0 0 0], ...
		'HandleVisibility','callback', ...
		'HorizontalAlignment','right', ...
		'Position',[-3.35869 0.505251 0], ...
		'Tag','Text4', ...
		'Visible','off');
	set(get(c,'Parent'),'ZLabel',c);
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'FontWeight','demi', ...
		'HorizontalAlignment','left', ...
		'Position',[313.5 249.75 111 11.25], ...
		'String','Distribution', ...
		'Style','text', ...
		'Tag','StaticText1');
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'Callback','close', ...
		'Position',[320.25 18 89.25 22.5], ...
		'String','Close', ...
		'Tag','Pushbutton1');
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'Callback','qtool(''redraw'')', ...
		'Position',[313.5 83.25 114 162.75], ...
		'String',jmat9, ...
		'Style','listbox', ...
		'Tag','Listbox2', ...
		'Value',10);
	kstr.ohandle = b ;
	b = uicontrol('Parent',a, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'FontSize',14, ...
		'FontWeight','bold', ...
		'ForegroundColor',[0 0 1], ...
		'Position',[326.25 279 84.75 15], ...
		'String','Q Tool', ...
		'Style','text', ...
		'Tag','StaticText2');

	set(kstr.fig,'UserData',kstr) ;
	qtool('redraw') ;
end 
