%PLSLOGO Generates PLS_Toolbox CR surface logo.
%
%I/O: plslogo

% Copyright Eigenvector Research, Inc. 1998
%Licensee shall not re-compile, translate or convert "M-files" contained
% in PLS_Toolbox for use with any software other than MATLAB®, without
% written permission from Eigenvector Research, Inc.
% BMW

p = []; nmap = [];  %pre-assign so we don't get errors on depfun calls
load plslogo
figure('Color',[1 1 1],'NumberTitle','off', ...
    'Name','PLS_Toolbox','Position',[80 90 640 460]);
axes('CameraPosition', [45 20 22],...
    'CameraTarget',[21 7 7], ...
    'CameraUpVector',[0 0 1], ...
    'CameraViewAngle',57, ...
    'DataAspectRatio', [1 .5 .9],...
    'Position',[0 0 1 1], ...
    'Visible','on', ...
    'XLim',[1 42], ...
    'YLim',[1 15], ...
    'ZLim',[0 20], ...
	'Xtick',[1 21 41], ...
	'Xticklabel',['MLR';'PLS';'PCR'],...
	'fontname','times', ...
	'fontsize',14);
%	'Zscale','log');
s = surface(p', ...
    'EdgeColor',[.4 0 0], ...
    'FaceColor',[0.8 0.2 0.2], ...
    'FaceLighting','phong', ...
    'AmbientStrength',0.3, ...
    'DiffuseStrength',0.6, ... 
    'Clipping','off',...
    'BackFaceLighting','lit', ...
    'SpecularStrength',1, ...
    'SpecularColorReflectance',1, ...
    'SpecularExponent',7);
l1 = light('Position',[21 7 13], ...
    'style','local', ...
    'Color',[0.8 0.7 0]);
l2 = light('Position',[25 11 25], ...
    'Color',[1 1 0]);
xl = xlabel('Continuum Parameter','fontname','times', ...
'fontsize',18,'fontweight','bold','position',[33 20 0]);
yl = ylabel('Number of LVs','fontname','times', ...
'fontsize',18,'fontweight','bold','position',[33 3 -8.9]);
zl = zlabel('PRESS','fontname','times', ...
'fontsize',18,'fontweight','bold');
shading interp
set(s,'Edgecolor',[.2 .2 .2])
colormap(nmap)
