%% readVisionAirSampleXML reads sample xml exported from Vision Air
%
% DESCRIPTION:
% readVisionAirSampleXML read sample data exported from Vision Air as XML.
% Thus Vision Air spectral data can be imported in Matlab and
% analysed with Eigenvector's PLS toolbox.
% Input is an xml data file generated by exporting data from the Vision Air
% software, the output an Eigenvector's dataset object. The object has a
% number of metadata encoded in the label, class and axisscales.
% Qualitative results are included as classes. Quantitative results in the
% dsy object and as axisscale. Using the plotgui function or dataset editor
% in the PLS_Toolbox/Solo one can plot the objects and visualize them by
% classes and axisscales.
% Only spectra with the same number of variables are supported. The first
% valid spectrum determines the number of variables. If spectra with
% noncompatible wavelength scales are found a warning is issued and NaN is
% used for spectral values.
%
% SYNTAX:
%   [dsx, dsy] = readVisionAirSampleXML(fn)
%
% INPUT:
%        fn  : filename of an xml file generated exporting data from the
%              Vision Air software
%
% OUTPUT:
%       dsx   : dataset object of the spectral data stored in the 'fn' xml
%               file. The following metadata is included:
%               - wavelength scale (axisscale)
%               - Time of analysis in UTC time (axisscale)
%               - Predicted values (axisscale)
%               - Secondary values e.g. TSQ and Q-residual (axisscale)
%               - UDF's (class)
%               - Predicted class for qualitative applications (class)
%               - Outlier, event and product limit status (class)
%               - Instrument serial number (class)
%               - Operating procedure (class)
%               - Sample information values (typical the user for the
%                 pharma versions of Vision Air) (label)
%       dsy   : dataset object of the reference and predicted values stored
%               in the 'fn' xml file. NaN is used if no values are present.
%               If fn does not contain any quantitative predictions is dsy
%               empty. The object contains both predicted and reference
%               values which van be retrived as: dsy.reference or
%               dsy.predicted. The metadata is identical to dsx where
%               relevant.
%
% EXAMPLES
%      [dsx, dsy] = me_readVisionAirSampleXML('fn.xml');
%      Plot the spectra: plotgui(dsx')
%      Get predicted values: dsy.predicted.data
%      Get reference values: dsy.reference.data
%
% Made for automatic translation [Y/N]: [N]

% Author : Stefano Gianoli
% Creation date : 2016-12-13
%
% Copyright (c) 2016-2019 by Metrohm AG, Ionenstr, 9100 Herisau, Switzerland,
% all rights reserved


%% Init Java



% check if the package is already on java class path. If not add it.
%pkgName = 'xmlparser-1.1.0.jar';


