function createcachedb(obj,force)
%CREATECACHEDB Create model cache database if needed. 

%Copyright Eigenvector Research, Inc. 2010
%Licensee shall not re-compile, translate or convert "M-files" contained
% in PLS_Toolbox for use with any software other than MATLAB®, without
% written permission from Eigenvector Research, Inc.

dbobj = obj.dbobject;

if nargin<2
  force = 0;
end

if ~force
  %Check for existing database.
  mytbls = dbobj.runquery('SELECT * FROM sys.systables where tabletype = ''T''');
  if ~isempty(mytbls{1}) && all(ismember({'PROJECT'    'CACHE'    'LINK'    'SOURCEATTRIBUTES'    'SOURCEDATA'},mytbls(:,2)))
    %Tables are there.
    updateCache(dbobj)
    return
  end
end
%Do a full shutdown and delete any existing database for testing purposes,
%remove this in production.
dbobj.shutdown_derby;
if isdir(fullfile(dbobj.location,dbobj.dbname))
  rmdir(fullfile(dbobj.location,dbobj.dbname),'s');
end

%------ DROP TABLES -----
%Have to drop tables in correct order because of constraints.
try
  myqry = 'DROP TABLE evri_cache_db.sourceData';
  dbobj.runquery(myqry);
end
try
  myqry = 'DROP TABLE evri_cache_db.sourceAttributes';
  dbobj.runquery(myqry);
end
try
  myqry = 'DROP TABLE evri_cache_db.link';
  dbobj.runquery(myqry);
end
try
  myqry = 'DROP TABLE evri_cache_db.cache';
  dbobj.runquery(myqry);
end
try
  myqry = 'DROP TABLE evri_cache_db.project';
  dbobj.runquery(myqry);
end


%------ PROJECT TABLE ------
myqry = [ 'CREATE TABLE evri_cache_db.project '...
'('...
'projectID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),' ...  
'name VARCHAR(100) NOT NULL,'...
'folder VARCHAR(500) NOT NULL,'...
'date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,'...
'notes VARCHAR(2000),'...
'CONSTRAINT PROJECT_PK PRIMARY KEY (projectID)'...
')']; 

dbobj.runquery(myqry);

%------ CACHE TABLE ------
myqry = [ 'CREATE TABLE evri_cache_db.cache '...
'('...
'cacheID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),' ...  
'projectID INTEGER NOT NULL,'...
'name VARCHAR(200) NOT NULL,'...
'description VARCHAR(1000) NOT NULL,'...
'type VARCHAR(100) NOT NULL,'...
'cacheDate DOUBLE,'...
'notes VARCHAR(2000),'...
'CONSTRAINT CACHE_PK PRIMARY KEY (cacheID),'...
'CONSTRAINT CACHE_FK FOREIGN KEY (projectID) REFERENCES evri_cache_db.project(projectID) ON DELETE CASCADE'...
')']; 
dbobj.runquery(myqry);


%------ LINK TABLE ------
myqry = [ 'CREATE TABLE evri_cache_db.link '...
'('...
'linkID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),' ...
'cacheID INTEGER NOT NULL,'...
'childID INTEGER NOT NULL,'...
'CONSTRAINT LINK_PK PRIMARY KEY (linkID),'...
'CONSTRAINT LINK_FK FOREIGN KEY (cacheID) REFERENCES evri_cache_db.cache(cacheID) ON DELETE CASCADE'...
')'];
dbobj.runquery(myqry);

%------ SOURCE ATTRIBUTES TABLE ------
myqry = [ 'CREATE TABLE evri_cache_db.sourceAttributes '...
'('...
'sourceAttributesID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),' ...
'name VARCHAR(100) NOT NULL,'...
'dataType VARCHAR(100) NOT NULL,'...
'CONSTRAINT SOURCEATTRIBUTES_PK PRIMARY KEY (sourceAttributesID)'...
')'];
dbobj.runquery(myqry);

%------ SOURCE DATA TABLE ------
myqry = [ 'CREATE TABLE evri_cache_db.sourceData '...
'('...
'sourceDataID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),' ...
'cacheID INTEGER NOT NULL,'...
'sourceAttributesID INTEGER NOT NULL,'...
'valChar VARCHAR(3000),'...
'valNum DOUBLE,'...
'CONSTRAINT SOURCEDATA_PK PRIMARY KEY (sourceDataID),'...
'CONSTRAINT SOURCEDATA_CACHE_FK FOREIGN KEY (cacheID) REFERENCES evri_cache_db.cache(cacheID) ON DELETE CASCADE,'...
'CONSTRAINT SOURCEDATA_SOURCEATTRIBUTES_FK FOREIGN KEY (sourceAttributesID) REFERENCES evri_cache_db.sourceAttributes(sourceAttributesID) ON DELETE CASCADE'...
')'];
dbobj.runquery(myqry);

updateCache(dbobj)

% %------ SOURCE DATA TABLE ------
% myqry = [ 'CREATE TABLE evri_cache_db.sourceDataXML '...
% '('...
% 'sourceDataID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),' ...
% 'cacheID INTEGER NOT NULL,'...
% 'valXML LONG VARCHAR,'...
% 'CONSTRAINT SOURCEDATA_PK PRIMARY KEY (sourceDataID),'...
% 'CONSTRAINT SOURCEDATA_CACHE_FK FOREIGN KEY (cacheID) REFERENCES evri_cache_db.cache(cacheID) ON DELETE CASCADE,'...
% ')'];
% dbobj.runquery(myqry)


function updateCache(dbo)
%Run updates on database.
%These updates should alway run in series and include checks. Be extremely
%careful when changing any of this code because database may be in any
%number of states.

%Add views.
myviews1 = dbo.runquery('SELECT * FROM sys.systables where tabletype = ''V''');
if isempty(myviews1{1}) || ~all(ismember({'VIEW_CACHE_WITH_NAME'},myviews1(:,2)))
  %Create view for lineage.
  qrystr = ['CREATE VIEW evri_cache_db.view_Cache_with_name (vProjectID, vCacheID,vName,vType,vCacheName,vCacheDate) AS '...
         'SELECT C.projectID, C.cacheID, SD.valChar, C.type, C.name, C.cacheDate FROM evri_cache_db.sourceData SD, '...
         'evri_cache_db.cache C, evri_cache_db.sourceAttributes SA  WHERE '...
         'SD.cacheID=C.cacheID AND SD.sourceAttributesID=SA.sourceAttributesID AND SA.name=''name'''];
  dbo.runquery(qrystr);
end
