
%VARIABLECOMPARE Compare included variables in models from Diviner results.
%   Create variable consensus plot of models generated by Diviner. Pass in
%   all the results of Diviner and consensus plots will be created for all
%   models. Optionally, pass in a vector of indices of specific models that
%   should be used to generate the plots.
%
%  INPUTS:
%   resultstable  = X-block (predictor block) class "double" or "dataset",
%              X  = Y-block (predicted block) class "double" or "dataset",
%            inds = double vector of model indices to use for
%                   visualization.
%
% I/O: variablecompare(results,x);
% I/O: variablecompare(results,x,inds); % use specific model indices
%
%See also: PLS PCA MODELOPTIMIZER ANALYSIS PREPROCESS

%Copyright Eigenvector Research, Inc. 2024
%Licensee shall not re-compile, translate or convert "M-files" contained
% in PLS_Toolbox for use with any software other than MATLAB®, without
% written permission from Eigenvector Research, Inc.
