function [a,b] = regcon(mod,xmn,ymn,xst,yst);
%REGCON Converts regression model to y = ax + b form.
%  REGCON can be used to convert a model (mod) generated by
%  the functions PLS, PCR, or MLR. The outputs are the 
%  regression coefficients (a) and the intercept (b) such that 
%  y = ax + b. In this case the I/O syntax is:
%
%I/O: [a,b] = regcon(mod);
%
%  Notes: 
%  (1) REGCON can will convert a regression model which uses Mean
%      Centering, Autoscaling, or None as the preprocessing. Any other
%      preprocessing will be rejected and cause an error.
%  (2) If the model was built with some variables excluded,
%      REGCON will infill with zeros as appropriate so that the output
%      can be used on the original X-block with all variables present.
%
%  REGCON can also be used to convert the individual parts of a
%  regression model, including the column vector of regression
%  coefficients (regv), predictor variable means (xmn), 
%  predicted variable means (ymn), predictor variable scaling 
%  (xst), and predicted variable scaling (yst).  If xmn or ymn 
%  is not supplied or is set equal to 0 or [], then it is assumed 
%  to be zero (i.e. no centering was used in the model). If xst 
%  or yst is not supplied or is set equal to 0 or [], then it is 
%  assumed to be one (i.e. no scaling was used in the model). 
%
%I/0: [a,b] = regcon(regv,xmn,ymn,xst,yst);
%
%Examples:
%  [a,b] = regcon(mod);                  % using REGRESSION model
%  [a,b] = regcon(regv,xmn,ymn);         % mean centered only
%  [a,b] = regcon(regv,xmn,ymn,xst,yst); % mean centered and scaled
%  [a,b] = regcon(regv,xmn,ymn,[],yst);  % x data centered but not scaled
%  [a,b] = regcon(regv,0,0,xst,yst);     % x and y scaled by not centered
%
%See also: ANALYSIS, AUTO, MNCN, MODLPRED, MODLRDER, PCR, PLS, POLYTRANSFORM, RIDGE

% Copyright © Eigenvector Research, Inc. 1997
% Licensee shall not re-compile, translate or convert "M-files" contained
%  in PLS_Toolbox for use with any software other than MATLAB®, without
%  written permission from Eigenvector Research, Inc.
%bmw 7/97
%bmw 3/98
%bmw 3/99
%bmw 8/02 changed to support 3.0 model format
%jms 8/05 fixed error when modeltype isn't three characters
%   -improved error messages
%   -allow basic support of PLSDA
%jms 11/05 -added help for preprocessing types. Fixed error message.

if nargin == 0; mod = 'io'; end
varargin{1} = mod;
if ischar(varargin{1});
  options = [];
  if nargout==0; clear a; evriio(mfilename,varargin{1},options); else; a = evriio(mfilename,varargin{1},options); end
  return; 
end
modelflag = 0;
if ismodel(mod)
  if ismember(lower(mod.modeltype),{'pls' 'pcr' 'plsda' 'mlr'})
    modelflag = 1;
    if length(mod.detail.preprocessing{1}) > 1
      error('"Multiple step" X-block preprocessing methods are not supported')
    elseif length(mod.detail.preprocessing{2}) > 1
      error('"Multiple step" Y-block preprocessing methods are not supported')
    else
      bb = mod.reg;
      [nxv,nyv] = size(bb);
      if isempty(mod.detail.preprocessing{1}) % No X-block preprocessing
        xst = ones(1,nxv);
        xmn = zeros(1,nxv);
      else
        xmeth = mod.detail.preprocessing{1}.description;
        if strcmp(xmeth,'Mean Center')
          xst = ones(1,nxv);
          xmn = mod.detail.preprocessing{1}.out{1};
        elseif strcmp(xmeth,'Autoscale')
          xst = mod.detail.preprocessing{1}.out{2};
          xmn = mod.detail.preprocessing{1}.out{1};
        else
          error(['X-block preprocessing method "' xmeth '" not supported'])
        end
      end
      if isempty(mod.detail.preprocessing{2}) % No Y-block preprocessing
        yst = ones(1,nyv);
        ymn = zeros(1,nyv);
      else
        ymeth = mod.detail.preprocessing{2}.description;
        if strcmp(ymeth,'Mean Center')
          yst = ones(1,nyv);
          ymn = mod.detail.preprocessing{2}.out{1};
        elseif strcmp(ymeth,'Autoscale')
          yst = mod.detail.preprocessing{2}.out{2};
          ymn = mod.detail.preprocessing{2}.out{1};
        else
          error(['Y-block preprocessing method "' ymeth '" not supported'])
        end
      end
    end
  else
    error(['Models of type ' mod.modeltype ' not supported'])
  end
else
  bb = mod;
  [nxv,nyv] = size(mod);
  if nargin == 1
    xmn = 0; ymn = 0; xst = 0; yst = 0;
  elseif nargin == 2
    ymn = 0; xst = 0; yst = 0;
  elseif nargin == 3
    xst = 0; yst = 0;
  elseif nargin == 4
    yst = 0;
  end
end
if (xmn == 0 | isempty(xmn))
  xmn = zeros(1,nxv);
end
if (xst == 0 | isempty(xst))
  xst = ones(1,nxv);
end
if (ymn == 0 | isempty(ymn))
  ymn = zeros(1,nyv);
end
if (yst == 0 | isempty(yst))
  yst = ones(1,nyv);
end

%make sure not to propogate bad standard deviation values back through
badsd = ~isfinite(xst)|xst==0;
xst(badsd) = 1;
xmn(badsd) = 0;

b = -((xmn./xst)*bb).*yst + ymn;
a = diag(yst)*(bb'./xst(ones(nyv,1),:));
  
% Check for excluded variables
if modelflag == 1
  org_xsize = mod.datasource{1}.size;
  if org_xsize(1,2) ~= nxv  % Must be excluded variables
    newa = zeros(nyv,org_xsize(1,2));
    newa(:,mod.detail.includ{2}) = a;
    a = newa;
  end
end
